#pragma once
// Warmth Fabric - detail/macros.hpp
// Windows SDK headers define a number of all-caps identifiers as macros that
// collide with enumerator names (ERROR, NONE, OVERFLOW, MIN, MAX, ...). This
// header is included immediately before any enum that uses such names so that
// the macros can never silently rewrite an enumerator. #undef on a non-macro is
// harmless and idempotent.
#undef ERROR
#undef INVALID
#undef FAILED
#undef READY
#undef NONE
#undef UNKNOWN
#undef OVERFLOW
#undef UNDERFLOW
#undef PING
#undef PONG
#undef HELLO
#undef REPORT
#undef SHUTDOWN
#undef REPLICA
#undef TRIGGER
#undef MIN
#undef MAX
#undef ABS
#undef DELETE
#undef LOCAL
#undef DERIVED
#undef MEASURED
#undef VALID
#undef PARTIAL
#undef COLD
#undef WARM
#undef HOT
#undef STALE
#undef EVICTED
#undef PREPARING
#undef DISCOVERED
#undef TERMINATED
#undef ADMITTED
#undef COOLING
#undef EVICTING
#undef NOT_STARTED
#undef MODEL_WEIGHTS
#undef ADAPTERS
#undef KERNEL_ARTIFACTS
#undef EXECUTION_GRAPHS
#undef ALLOCATOR_POOLS
#undef APPLICATION_DEFINED
#undef STORAGE_ONLY
#undef HOST_ONLY
#undef MIRRORED
#undef SUSPECT
#undef ESTIMATED
#undef REPORTED
#undef STALE
#undef EVICTED
#undef DISCOVERED
#undef PREPARING
#undef WARM
#undef HOT
#undef IDLE_ELAPSED
#undef MEMORY_PRESSURE
#undef DEVICE_RESET
#undef PROCESS_RESTART
#undef DEPENDENCY_GENERATION_CHANGE
#undef ARTIFACT_REPLACEMENT
#undef POLICY_GENERATION_CHANGE
#undef MODEL_REVISION_CHANGE
#undef ADAPTER_SET_CHANGE
#undef TOKENIZER_CHANGE
#undef KERNEL_GENERATION_CHANGE
#undef GRAPH_GENERATION_CHANGE
#undef COMPUTE_CAPABILITY_CHANGE
#undef DEVICE_CHANGE
#undef DEPENDENCY_CORRUPTION
#undef INTEGRITY_FAILURE
#undef RUNTIME_COMPILER_CHANGE
