add_executable(warmth_bench benchmark_warmth.cpp)
target_link_libraries(warmth_bench PRIVATE warmth)
target_compile_features(warmth_bench PRIVATE cxx_std_20)
if(WIN32)
    target_link_libraries(warmth_bench PRIVATE ws2_32)
endif()
if(MSVC)
    target_compile_options(warmth_bench PRIVATE /W4 /WX /permissive- /Zc:__cplusplus /EHsc)
else()
    target_compile_options(warmth_bench PRIVATE -Wall -Wextra -Werror)
endif()
